dependencies {
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "64.0.2"
	testIntegrationCompile project(":apps:change-tracking:change-tracking-api")
	testIntegrationCompile project(":apps:change-tracking:change-tracking-spi")
	testIntegrationCompile project(":apps:change-tracking:change-tracking-store-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}