dependencies {
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "64.0.2"
	testCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "92.1.0"
	testCompile project(":apps:archived:sync-api")
	testCompile project(":apps:archived:sync-service")
	testCompile project(":core:petra:petra-string")

	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}