name: Scheduled Merge with Master
on:
   schedule:
   - cron: '0 9 * * *'
   workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge upgrade-test-suite-workflow with master 
        run: |
          git config user.name 'Jorge Avalos'
          git config user.email 'jorge.avalos@liferay.com'
          git fetch origin upgrade-test-suite-workflow
          git checkout origin/upgrade-test-suite-workflow
          git switch -c upgrade-test-suite-workflow
          git merge origin/master
          git push origin upgrade-test-suite-workflow --force
