name: Create Pull Request and Comment
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Scheduled Empty Commit Branch']
    types: [completed]
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUBPRTOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request with gh
        run: |
          gh repo sync javalosjr96/liferay-portal
