name: Sync with Master
on:
   schedule:
   - cron: '0 9 * * *'
   workflow_dispatch:
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUBPRTOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request with gh
        run: |
          gh repo sync javalosjr96/liferay-portal
