name: Sync Repository

on:
  workflow_dispatch:
  push: { branches: [ main ] }  # Adjust branch to watch for pushes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: repo-sync/github-sync@v3  # Replace with the latest version
        with:
          source: "liferay/liferay-portal"
          destination: "javalosjr96/liferay-portal"
          branch: "master" 
