name: Merge with Master
on:
   schedule:
   - cron: '0 9 * * *'
   workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Sync to Upstream Repository
      uses: mheene/sync-upstream-repo@v0.1.2
      with:
      # GitHub public upstream repo
        upstream_repo: https://github.com/liferay/liferay-portal.git
