name: Create Pull Request and Comment (Force Push)
on: [push]  

jobs:
  create-pull-request:  
    runs-on: ubuntu-latest  
    env:                                                
        GITHUB_TOKEN: ${{ secrets.GITHUBPRTOKEN }} 
    steps:
      - uses: actions/checkout@v3  
      - name: Create Pull Request with gh
        run: |  
          gh pr create --title "Force Pushed Changes (review recommended)" --body "ci:test:upgrade" --head ${{ github.ref }}


