name: Scheduled Empty Commit Branch
on:
   schedule:
   - cron: '30 5 * * *'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creating Empty PR 
        run: |
          git config user.name 'Jorge Avalos'
          git config user.email 'jorge.avalos@liferay.com'
          git switch -c upgrade-suite-test
          git push origin upgrade-suite-test --force
          git commit -m "Automated Empty PR" --allow-empty
          git push origin upgrade-suite-test
